app.base-url=/api/v1/
app.base-images-url=http://192.168.0.13:8181/posts/
app.base-images-path=./uploads/posts/

# Database - Hardcoded (PostgreSQL dockerizado)
spring.datasource.url=jdbc:postgresql://localhost:5432/reuse
spring.datasource.username=postgres
spring.datasource.password=1234

# jpa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logging
logging.level.root=INFO
logging.level.br.com.lcsz.reuseplus=DEBUG